# Generated by Django 3.2.4 on 2021-06-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltable',
            name='supervisor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
